### ISSUE TITLE
Styling and Fucntion documentation for Mapper.py

### ISSUE THREAD

**Issue by Yash3667** [Yash3667/GeigerToKML#1]
Hi Justin,

it would be best if we followed a single style of writing for the entire module. Currently, all the test scripts are written using camel casing and it would be the most efficient system to change Mapper.py to support similar casing. 

Also, make sure to add function explanations and parameter use using the multi line comments underneath the function definition.

Thanks! 
Yash

**Comment by jraizes** [comment]
Sorry about that. F some reason, my documentation comments didn't go
through when I pushed. I'll make sure to get those pushed through and
fix the naming style shortly.

On 02/18/2016 05:14 AM, Yash Gupta wrote:

> Hi Justin,
> 
> it would be just if we followed a single style of writing for the
> entire module. Currently, all the test scripts are written using camel
> casing and it would be the most efficient system to change Mapper.py
> to support similar casing.
> 
> Also, make sure to add function explanations and parameter use using
> the multi line comments underneath the function definition
> 
> Eg:
> def foo():
> """
> Comments here
> """
> 
> Thanks!
> 
> Yash
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Yash3667/GeigerToKML/issues/1.

## 

Justin Raizes

Undergraduate Researcher
Storage Systems Research Center,
University of California, Santa Cruz
